USE caudillos;
TRUNCATE teams;
INSERT INTO teams (id,name,alias,short,logo) VALUES (1,'Chihuahua','Caudillos','CAU','public/teams/logo_001_caudillos.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (2,'Saltillo','Dinos','DIN','public/teams/logo_002_dinos.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (3,'Monterrey','Fundidores','FUN','public/teams/logo_003_fundidores.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (4,'Tijuana','Galgos','GGS','public/teams/logo_004_galgos.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (5,'Querétaro','Gallos Negros','GLS','public/teams/logo_005_gallos.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (6,'Cd Juárez','Jefes','JEF','public/teams/logo_006_jefes.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (7,'Cd México','Mexicas','MEX','public/teams/logo_007_mexicas.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (8,'Naulcalpan','Raptors','RAP','public/teams/logo_008_raptors.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (9,'Ixtacalco','Reds','RED','public/teams/logo_009_reds.png');
INSERT INTO teams (id,name,alias,short,logo) VALUES (10,'Jalisco','Reyes','REY','public/teams/logo_010_reyes.png');
