USE caudillos;
TRUNCATE teams;
INSERT INTO teams (id,name, alias, short, logo) VALUES (1, 'Dallas ', 'Cowboys', 'DAL', 'cowboys.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (2, 'New York G', 'Giants', 'NYG', 'giants.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (3, 'Philadelphia ', 'Eagles', 'PHI', 'eagles.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (4, 'Washington ', 'Football', 'WAS', 'redskins.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (5, 'Chicago ', 'Bears', 'CHI', 'bears.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (6, 'Detroit ', 'Lions', 'DET', 'lions.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (7, 'Green Bay ', 'Packers', 'GB', 'packers.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (8, 'Minnesota ', 'Vikings', 'MIN', 'vikings.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (9, 'Atlanta ', 'Falcons', 'ATL', 'falcons.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (10, 'Carolina ', 'Panthers', 'CAR', 'panthers.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (11, 'New Orleans ', 'Saints', 'NO', 'saints.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (12, 'Tampa Bay ', 'Buccaneers', 'TB', 'buccaneers.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (13, 'Arizona ', 'Cardinals', 'ARI', 'cardinals.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (14, 'Los Angeles R', 'Rams', 'LAR', 'rams.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (15, 'San Francisco ', '49ers', 'SF', '49ers.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (16, 'Seattle ', 'Seahawks', 'SEA', 'seahawks.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (17, 'Buffalo ', 'Bills', 'BUF', 'bills.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (18, 'Miami ', 'Dolphins', 'MIA', 'dolphins.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (19, 'New England', 'Patriots', 'NE', 'patriots.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (20, 'New York J', 'Jets', 'NYJ', 'jets.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (21, 'Baltimore ', 'Ravens', 'BAL', 'ravens.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (22, 'Cincinnati ', 'Bengals', 'CIN', 'bengals.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (23, 'Cleveland ', 'Browns', 'CLE', 'browns.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (24, 'Pittsburgh ', 'Steelers', 'PIT', 'steelers.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (25, 'Houston ', 'Texans', 'HOU', 'texans.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (26, 'Indianapolis ', 'Colts', 'IND', 'colts.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (27, 'Jacksonville ', 'Jaguars', 'JAX', 'jaguars.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (28, 'Tennessee ', 'Titans', 'TEN', 'titans.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (29, 'Denver ', 'Broncos', 'DEN', 'broncos.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (30, 'Kansas City ', 'Chiefs', 'KC', 'chiefs.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (31, 'Las Vegas', 'Raiders', 'LAS', 'raiders.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (32, 'Los Angeles C', 'Chargers', 'LAC', 'chargers.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (33, 'Bye', 'Bye', 'Bye', 'nacional.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (34, 'Irving', 'Irving', 'Irv', 'americana.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (35, 'Carter', 'Carter', 'Car', 'nacional.png');
INSERT INTO teams (id,name, alias, short, logo) VALUES (36, 'TBD', 'TBD', 'TBD', 'nflplayofflogo.png');
